"""Added 'about' to User model

Revision ID: be2bc3fbcf74
Revises: f5f0e9dd3f93
Create Date: 2018-05-09 12:07:36.728459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2bc3fbcf74'
down_revision = 'f5f0e9dd3f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
