"""trying new deletions

Revision ID: 305589917aae
Revises: 9b348560555f
Create Date: 2018-08-14 10:21:10.850705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305589917aae'
down_revision = '9b348560555f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('pub_date', sa.String(length=32), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_item_timestamp'), 'item', ['timestamp'], unique=False)
    op.create_table('sb_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_sb_file_timestamp'), 'sb_file', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sb_file_timestamp'), table_name='sb_file')
    op.drop_table('sb_file')
    op.drop_index(op.f('ix_item_timestamp'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
