"""Created new db for many-to-many relations

Revision ID: 4e505a57a151
Revises:
Create Date: 2018-08-15 10:33:16.662913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e505a57a151'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casc',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sb_id', sa.String(length=32), nullable=True),
                    sa.Column('url', sa.String(length=128), nullable=True),
                    sa.Column('name', sa.String(length=32), nullable=True),
                    sa.Column('total_data', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('sb_id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sb_id', sa.String(length=32), nullable=True),
                    sa.Column('url', sa.String(length=128), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('total_data', sa.Integer(), nullable=True),
                    sa.Column('file_count', sa.Integer(), nullable=True),
                    sa.Column('start_date',
                              sa.String(length=32), nullable=True),
                    sa.Column('end_date', sa.String(length=32), nullable=True),
                    sa.Column('pub_date', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('sb_id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_item_timestamp'),
                    'item', ['timestamp'], unique=False)
    op.create_table('problem_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('issue', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_problem_item_timestamp'),
                    'problem_item', ['timestamp'], unique=False)
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sb_id', sa.String(length=32), nullable=True),
                    sa.Column('url', sa.String(length=128), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('total_data', sa.Integer(), nullable=True),
                    sa.Column('item_count', sa.Integer(), nullable=True),
                    sa.Column('file_count', sa.Integer(), nullable=True),
                    sa.Column('start_date',
                              sa.String(length=32), nullable=True),
                    sa.Column('end_date', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('sb_id')
                    )
    op.create_index(op.f('ix_project_timestamp'),
                    'project', ['timestamp'], unique=False)
    op.create_table('sb_file',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('content_type',
                              sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_sb_file_timestamp'),
                    'sb_file', ['timestamp'], unique=False)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=128), nullable=True),
                    sa.Column('password_hash',
                              sa.String(length=128), nullable=True),
                    sa.Column('last_seen', sa.DateTime(), nullable=True),
                    sa.Column('about', sa.String(length=140), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'),
                    'user', ['username'], unique=True)
    op.create_table('assoc_casc_item',
                    sa.Column('casc_id', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], )
                    )
    op.create_table('assoc_casc_prob_item',
                    sa.Column('casc_id', sa.Integer(), nullable=True),
                    sa.Column('prob_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
                    sa.ForeignKeyConstraint(['prob_item_id'],
                                            ['problem_item.id'], )
                    )
    op.create_table('assoc_casc_project',
                    sa.Column('casc_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
                    )
    op.create_table('assoc_casc_sbfile',
                    sa.Column('casc_id', sa.Integer(), nullable=True),
                    sa.Column('sbfile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
                    sa.ForeignKeyConstraint(['sbfile_id'], ['sb_file.id'], )
                    )
    op.create_table('assoc_item_sbfile',
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('sbfile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['sbfile_id'], ['sb_file.id'], )
                    )
    op.create_table('assoc_proj_item',
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
                    )
    op.create_table('assoc_proj_prob_item',
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('prob_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['prob_item_id'],
                                            ['problem_item.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
                    )
    op.create_table('assoc_proj_sbfile',
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('sbfile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.ForeignKeyConstraint(['sbfile_id'], ['sb_file.id'], )
                    )
    op.create_table('fiscal_year',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sb_id', sa.String(length=32), nullable=True),
                    sa.Column('url', sa.String(length=128), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=32), nullable=True),
                    sa.Column('total_data', sa.Integer(), nullable=True),
                    sa.Column('casc_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('sb_id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_fiscal_year_timestamp'),
                    'fiscal_year', ['timestamp'], unique=False)
    op.create_table('assoc_fy_item',
                    sa.Column('fy_id', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], )
                    )
    op.create_table('assoc_fy_prob_item',
                    sa.Column('fy_id', sa.Integer(), nullable=True),
                    sa.Column('prob_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
                    sa.ForeignKeyConstraint(['prob_item_id'],
                                            ['problem_item.id'], )
                    )
    op.create_table('assoc_fy_project',
                    sa.Column('fy_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
                    )
    op.create_table('assoc_fy_sbfile',
                    sa.Column('fy_id', sa.Integer(), nullable=True),
                    sa.Column('sbfile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
                    sa.ForeignKeyConstraint(['sbfile_id'], ['sb_file.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_fy_sbfile')
    op.drop_table('assoc_fy_project')
    op.drop_table('assoc_fy_prob_item')
    op.drop_table('assoc_fy_item')
    op.drop_index(op.f('ix_fiscal_year_timestamp'), table_name='fiscal_year')
    op.drop_table('fiscal_year')
    op.drop_table('assoc_proj_sbfile')
    op.drop_table('assoc_proj_prob_item')
    op.drop_table('assoc_proj_item')
    op.drop_table('assoc_item_sbfile')
    op.drop_table('assoc_casc_sbfile')
    op.drop_table('assoc_casc_project')
    op.drop_table('assoc_casc_prob_item')
    op.drop_table('assoc_casc_item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sb_file_timestamp'), table_name='sb_file')
    op.drop_table('sb_file')
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_problem_item_timestamp'), table_name='problem_item')
    op.drop_table('problem_item')
    op.drop_index(op.f('ix_item_timestamp'), table_name='item')
    op.drop_table('item')
    op.drop_table('casc')
    # ### end Alembic commands ###
