"""Del: SbFile.date_uplaoded. Add: Item.pub_date

Revision ID: 868b6fd5d93c
Revises: 9b348560555f
Create Date: 2018-08-14 10:09:33.826201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868b6fd5d93c'
down_revision = '9b348560555f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('pub_date', sa.String(length=32), nullable=True))
    op.drop_column('sb_file', 'date_uploaded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sb_file', sa.Column('date_uploaded', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('item', 'pub_date')
    # ### end Alembic commands ###
