"""ScienceBase and User tables

Revision ID: 8bb9aeb1967f
Revises: 
Create Date: 2018-05-03 10:47:39.079872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb9aeb1967f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fiscal_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_fiscal_year_timestamp'), 'fiscal_year', ['timestamp'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_item_timestamp'), 'item', ['timestamp'], unique=False)
    op.create_table('problem_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('issue', sa.String(length=128), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_problem_item_timestamp'), 'problem_item', ['timestamp'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sb_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.String(length=32), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_file_timestamp'), 'file', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_timestamp'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_problem_item_timestamp'), table_name='problem_item')
    op.drop_table('problem_item')
    op.drop_index(op.f('ix_item_timestamp'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_fiscal_year_timestamp'), table_name='fiscal_year')
    op.drop_table('fiscal_year')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('casc')
    # ### end Alembic commands ###
