"""Update SbFiles table with content_type, delete unused fields

Revision ID: 9b348560555f
Revises: be2bc3fbcf74
Create Date: 2018-08-10 10:23:46.087085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b348560555f'
down_revision = 'be2bc3fbcf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sb_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.String(length=32), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('casc_id', sa.Integer(), nullable=True),
    sa.Column('fy_id', sa.Integer(), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_sb_file_timestamp'), 'sb_file', ['timestamp'], unique=False)
    op.drop_index('ix_file_timestamp', table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sb_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('date_uploaded', sa.VARCHAR(length=32), nullable=True),
    sa.Column('file_count', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('casc_id', sa.INTEGER(), nullable=True),
    sa.Column('fy_id', sa.INTEGER(), nullable=True),
    sa.Column('proj_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['casc_id'], ['casc.id'], ),
    sa.ForeignKeyConstraint(['fy_id'], ['fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sb_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_file_timestamp', 'file', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_sb_file_timestamp'), table_name='sb_file')
    op.drop_table('sb_file')
    # ### end Alembic commands ###
