"""Added 'last_seen' to User model

Revision ID: f5f0e9dd3f93
Revises: 8bb9aeb1967f
Create Date: 2018-05-09 11:52:31.575080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f0e9dd3f93'
down_revision = '8bb9aeb1967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
